from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Save(object):
    def setupUi(self, Save):
        Save.setObjectName("Save")
        Save.resize(970, 638)
        self.vL_main = QtWidgets.QVBoxLayout(Save)
        self.vL_main.setObjectName("vL_main")
        self.pushButton_save = QtWidgets.QPushButton(Save)
        self.pushButton_save.setObjectName("pushButton_save")
        self.vL_main.addWidget(self.pushButton_save)
        self.checkBox_create_new_folder = QtWidgets.QCheckBox(Save)
        self.checkBox_create_new_folder.setObjectName("checkBox_create_new_folder")
        self.vL_main.addWidget(self.checkBox_create_new_folder)
        self.label_name_folder = QtWidgets.QLabel(Save)
        self.label_name_folder.setObjectName("label_name_folder")
        self.vL_main.addWidget(self.label_name_folder)
        self.lineEdit_name_folder = QtWidgets.QLineEdit(Save)
        self.lineEdit_name_folder.setObjectName("lineEdit_name_folder")
        self.vL_main.addWidget(self.lineEdit_name_folder)
        self.label_name_saves = QtWidgets.QLabel(Save)
        self.label_name_saves.setObjectName("label_name_saves")
        self.vL_main.addWidget(self.label_name_saves)
        self.lineEdit_name_saves = QtWidgets.QLineEdit(Save)
        self.lineEdit_name_saves.setObjectName("lineEdit_name_saves")
        self.vL_main.addWidget(self.lineEdit_name_saves)
        self.label_selected_folder = QtWidgets.QLabel(Save)
        self.label_selected_folder.setObjectName("label_selected_folder")
        self.vL_main.addWidget(self.label_selected_folder)
        self.scrollArea_saves = QtWidgets.QScrollArea(Save)
        self.scrollArea_saves.setWidgetResizable(True)
        self.scrollArea_saves.setObjectName("scrollArea_saves")
        self.sAWC = QtWidgets.QWidget()
        self.sAWC.setGeometry(QtCore.QRect(0, 0, 950, 428))
        self.sAWC.setObjectName("sAWC")
        self.vL_sAWC = QtWidgets.QVBoxLayout(self.sAWC)
        self.vL_sAWC.setObjectName("vL_sAWC")
        self.scrollArea_saves.setWidget(self.sAWC)
        self.vL_main.addWidget(self.scrollArea_saves)
        self.pushButton_back = QtWidgets.QPushButton(Save)
        self.pushButton_back.setObjectName("pushButton_back")
        self.vL_main.addWidget(self.pushButton_back)

        self.retranslateUi(Save)
        QtCore.QMetaObject.connectSlotsByName(Save)

    def retranslateUi(self, Save):
        _translate = QtCore.QCoreApplication.translate
        Save.setWindowTitle(_translate("Save", "Save my Save"))
        self.pushButton_save.setText(_translate("Save", "Save"))
        self.checkBox_create_new_folder.setText(_translate("Save", "Create new Saves folder"))
        self.label_name_folder.setText(_translate("Save", "Name for new folder:"))
        self.label_name_saves.setText(_translate("Save", "Name for my new Save:"))
        self.label_selected_folder.setText(_translate("Save", "Select folder for Save:"))
        self.pushButton_back.setText(_translate("Save", "Back"))
